import os

ANSWER_CACHE_TTL_DEFAULT = int(os.getenv("ANSWER_CACHE_TTL_DEFAULT", "21600"))
ANSWER_CACHE_TTL_CONTACT = int(os.getenv("ANSWER_CACHE_TTL_CONTACT", "14400"))
ANSWER_CACHE_TTL_GENERIC = int(os.getenv("ANSWER_CACHE_TTL_GENERIC", "86400"))
