global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'munbot_evolution_api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - evolution-api:8080

  - job_name: scheduler
    metrics_path: /metrics
    static_configs:
      - targets: ['scheduler-mcp:6001']

  - job_name: 'complaint-mcp'
    metrics_path: /metrics
    static_configs:
      - targets: ['complaints-mcp:7000']

  - job_name: 'mcp-core'
    metrics_path: /metrics
    static_configs:
      - targets: ['mcp-core:5000']

  - job_name: 'web-interface'
    metrics_path: /metrics
    static_configs:
      - targets: ['web-interface:3000']

  - job_name: 'docker_engine'
    static_configs:
      - targets:
          - cadvisor:8080           # (opcional, si añades cadvisor)
