apiVersion: 1

datasources:
  - name: CivicAnalytics
    uid: civic-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: munbot
    user: munbot
    secureJsonData:
      password: "1234"
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: false
    isDefault: false
    editable: true
